### ISSUE TITLE
Best way to use with smartphones?

### ISSUE THREAD

**Issue by nixoye** [JustSch/node-snapdrop-electron#1]
What would be the best way to be able to use this snapdrop fork with smartphones? The main snapdrop website is down and using the drbassman lan website doesnt seem to be compatible with this version

**Comment by JustSch** [comment]
what os are you using on your phone and computer? I haven't tested the mac version but i may be able to borrow a mac if it's an issue with the mac version. Otherwise, you should be able to access snapdrop by putting the ip it gives in your mobile browser. I myself have tested this with the windows and linux versions and safari on my iphone. If you have virtual machines setup it may give you the wrong ip first so if you click "click here for another network adapter ip" it cycle through all the local ip it finds and one should hopefully be able to connect. If all else fails it could be firewall blocking it but I can check to see if it's anything on my end first

**Comment by nixoye** [comment]
ah yeah that works. I thought since it included the LAN fix so it would automatically find it using the heroku instance drbassman has up

**Comment by JustSch** [comment]
My version runs entirely locally. Other instances probably will not be able to find it.

**Comment by JustSch** [comment]
I have made an update with clearer wording specifying to connect via the local ip in the browser

**Comment by nixoye** [comment]
> I have made an update with clearer wording specifying to connect via the local ip in the browser

thanks, do the desktop version update automatically?

**Comment by JustSch** [comment]
probably not but I may set that up in the future if it's not too hard to do
